### PR TITLE
Update to the latest version of github-pages

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by queryluke** [comment]
Upgrading the Gem with this pull request

@sdellis @phette23 @joshuago78 (and anyone else)
You'll need to run `bundle install` next time you're ready to develop. Otherwise you're going to get a .lock error

**Comment by jcoyne** [comment]
Run "bundle install" instead of "bundle update" or you risk modifying Gemfile.lock again

**Comment by queryluke** [comment]
@jcoyne sorry! thanks for clarifying (I've edited above in case anyone doesn't scroll down)

**Comment by phette23** [comment]
thanks for the heads up

**Pull request merged**
