### PR TITLE
PDF information sheet for linking from prospectus page

### PR DESCRIPTION
**Pull request by gmcharlt**

### CODE REVIEW

**Comment by sdellis** [comment]
What is on the pdf info sheet that can't be on the prospectus page?

**Comment by gmcharlt** [comment]
Content-wise, nothing. However, it exists as an artifact that will be used by the folks reaching out to potential sponsors, and a link (which need not be prominent) from the prospectus page will make  it easier for those folks to get at it.

**Comment by sdellis** [comment]
Seems like a pain to maintain both, but perhaps there's a use case for PDF the sponsorship committee has in mind - better printed layout that can't be done in CSS?

**Comment by gmcharlt** [comment]
As far as maintenance is concerned, while I don't necessarily expect that the information sheet will change, the budget and sponsorship committee can take charge of supplying any updated PDFs.

The main use case envisioned is giving potential sponsors a document that they can incorporate into a justification to their local powers that be to spend money on a sponsorship. We'll find out whether it helps or just gets ignored in due course.

As far as recasting the form, if you feel inspired to turn it into something that is not a PDF, please feel free, but for the moment it would be really handy if it ended up on the website. (Also see pull request 40).

**Pull request merged**
